#!/bin/sh

xrandr --output eDP-0 --mode "1920x1080" --rate "60.00"
xrandr --output eDP1 --mode "1920x1080" --rate "60.00"
xrandr --output eDP-1 --mode "1920x1080" --rate "60.00"
xrandr --output eDP-1-1 --mode "1920x1080" --rate "60.00"
xrandr --output eDP-2 --mode "1920x1080" --rate "60.00"
xrandr --output Virtual-0 --mode "1920x1080" --rate "60.00"
xrandr --output Virtual-1 --mode "1920x1080" --rate "60.00"
xrandr --output Virtual-2 --mode "1920x1080" --rate "60.00"
picom &
xset s off
xset s noblank
xset -dpms
dunst &
nm-applet &
blueman-applet &
flameshot &
xset r rate 220 40
~/.fehbg
