[pyprland]
plugins = [
    "scratchpads",
    "magnify",
]

# Configure scratchpads
[scratchpads.term]
command = "kitty --class=scratchterm"
animation = "fromTop"
size = "60% 80%"
lazy = true

[scratchpads.pavucontrol]
command = "pavucontrol"
animation = "fromBottom"
unfocus = "hide"
size = "80% 60%"
lazy = true
