#!/bin/sh

SYSTEM=(
    base
    base-devel
    linux
    linux-headers
)

GRAPHICS=(
    mesa 
    mesa-demos
    libva-intel-driver 
    vulkan-intel
    lib32-mesa
    lib32-vulkan-intel
    nvidia
    nvidia-utils
    nvidia-settings
    nvidia-prime
    lib32-nvidia-utils
    xf86-video-intel
    lib32-mesa
    prime-run
)

BASE_PKGS=(
  vim
  neovim-nightly
  git
  wget
  curl
  fish
  starship
  fzf
  zoxide
  tmux
  ripgrep
)

TERM_PKGS=(
  alacritty
  kitty
  ghostty
)

LSP_SERVERS=(
  lua-language-server
  python-lsp-server
  gopls
  vscode-langservers-extracted
  hyprls-git
)

FORMATTERS=(
  stylua
  prettier
  python-black
  python-isort
  shfmt
  yamlfmt
  clang
  go-tools
  prettierd
  google-java-format
)

DEVELOPMENT=(
    lazygit
    gcc
    rustup
    go
    python
    uv
    nodejs
    ollama  
)

BROWSERS=(
  brave-bin
)

GTK_PKGS=(
  gtk2
  gtk3
  gtk4
  gdk-pixbuf2
  libcups
  pango
  cairo
  gtk-update-icon-cache
  shared-mime-info
  hicolor-icon-theme
)

AUDIO=(
    pipewire
    pipewire-pulse
    pipewire-alsa
    pipewire-jack
    wireplumber
    pavucontrol
    helvum 
    qpwgraph
    jamesdsp
)

BLUETOOTH=(
    blueman
    bluez
    bluez-utils
    pipewire-bluetooth
)

HYPR_PKGS=(
    hyprland
    pyprland
    hypridle
    hyprland-qt-support
    hyprland-qtutils
    hyprlock
    hyprpicker
    rofi-wayland
    xdg-desktop-portal-hyprland
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
    xdg-desktop-portal
    grimblast-git
    waybar
    swaync
    swww
    wlogout
    wl-clipboard
    wlroots
    xwaylandvideobridge
    xwayland-run
    networkmanager
    network-manager-applet
    brightnessctl
    nautilus
    nwg-look
    papirus-icon-theme
    nordzy-hyprcursors
    python-pywal
    tty-colorscheme
)

PREFERRED_DM=(
  cosmic
)

BLUE='\033[1;34m'
NC='\033[0m'

install_package_group() {
  local group_name="$1"
  shift
  local packages=("$@")

  echo -e "\n${BLUE}Installing ${group_name}...${NC}"
  if paru -S --needed --noconfirm "${packages[@]}"; then
    echo "✔️  ${group_name} installed successfully"
  else
    echo "❌  Failed to install ${group_name}"
    return 1
  fi
}

install_package_group "System Packages" "${SYSTEM[@]}"
install_package_group "Graphics Packages" "${GRAPHICS[@]}"
install_package_group "Base Packages" "${BASE_PKGS[@]}"
install_package_group "Terminal Emulators" "${TERM_PKGS[@]}"
install_package_group "GTK Dependencies" "${GTK_PKGS[@]}"
install_package_group "LSP Servers" "${LSP_SERVERS[@]}"
install_package_group "Code Formatters" "${FORMATTERS[@]}"
install_package_group "Development Languages and tools" "${DEVELOPMENT[@]}"
install_package_group "Browser" "${BROWSERS[@]}"
install_package_group "Pipewire packages" "${AUDIO[@]}"
install_package_group "Bluetooth Packages" "${BLUETOOTH[@]}"
install_package_group "Hyprland packages" "${HYPR_PKGS[@]}"
# install_package_group "Preferred Desktop Manager" "${PREFERRED_DM[@]}"
