#!/bin/sh

set -e

# NOTE: SYSTEM PACKAGES
SYSTEM=(
    base
    base-devel
    linux-zen
    linux-zen-headers
)

# NOTE: GRAPHICS PACKAGES FOR INTEL AND NVIDIA
GRAPHICS=(
    mesa 
    mesa-utils
    mesa-demos
    libva-intel-driver 
    vulkan-intel
    lib32-mesa
    lib32-vulkan-intel
    dkms
    nvidia-dkms
    nvidia-utils
    nvidia-settings
    nvidia-prime
    lib32-nvidia-utils
    xf86-video-intel
    lib32-mesa
)

GAMING_PKGS=(
    steam 
    gamemode
    lib32-gamemode
    mangohud 
    lib32-mangohud
    vulkan-icd-loader 
    lib32-vulkan-icd-loader
)

# NOTE: THESE ARE SOME OF THE BASIC PACKAGES FOR FISH TO WORK AND HAVE GOOD EXPERIENCE USING TERMINAL OR TTY
BASE_PKGS=(
    vim
    neovim
    git
    git-delta
    wget
    curl
    fish
    starship
    fzf
    zoxide
    tmux
    ripgrep
    bat
    man
    stow
    eza
    bc
)

# NOTE: PACKAGES FOR TERMINAL
TERM_PKGS=(
    alacritty
    kitty
    ghostty
)

# NOTE: SOME PACKGES FOR PROGRAMMING LANGUAGES I LIKE
DEVELOPMENT=(
    lazygit
    gcc
    rustup
    go
    python
    uv
    jdk-openjdk
    maven
    gradle
    nodejs
    npm
    vite
    obsidian-bin
    joplin-appimage
)

LSP=(
    pyright
    lua-language-server
    jdtls
)

FORMATTERS=(
    stylua 
    python-black 
    python-isort 
    prettier 
    gofumpt 
    goimports-reviser
    rustfmt 
    shfmt 
    clang 
    sqlfluff 
    yamlfmt
    prettierd
    google-java-format
)

# NOTE: BROWERS I LIKE TO HAVE
BROWSERS=(
    brave-bin
    zen-browser-bin
)

# NOTE: PACKAGES FOR GTK TO RUN CORRECTLY
GTK_PKGS=(
    gtk2
    gtk3
    gtk4
    gdk-pixbuf2
    libcups
    pango
    cairo
    gtk-update-icon-cache
    shared-mime-info
    hicolor-icon-theme
)

# NOTE: PACKAGES TO RUN AUDIO THE BEST IN ARCH
AUDIO=(
    pipewire 
    pipewire-alsa 
    pipewire-audio 
    pipewire-pulse 
    pipewire-jack 
    pipewire-zeroconf 
    gst-plugin-pipewire 
    wireplumber 
    pipewire-docs
    pavucontrol
    helvum 
    qpwgraph
    jamesdsp
)

# NOTE: PACKAGES TO RUN VIDEO THE BEST IN ARCH
VIDEO=(
    mpv
    vlc
    ffmpeg
    imagemagick
)

# NOTE: PACKAGES FOR BLUETOOH
BLUETOOTH=(
    blueman
    bluez
    bluez-utils
)

# NOTE: PACKGES FOR HYPRLAND TO WORK WITH THE CONFIG I LIKE
HYPR_PKGS=(
    hyprland
    pyprland
    hypridle
    hyprland-qt-support
    hyprland-qtutils
    hyprlock
    hyprpicker
    rofi-wayland
    xdg-desktop-portal-hyprland
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
    xdg-desktop-portal
    grimblast-git
    waybar
    swaync
    swww
    wlogout
    wl-clipboard
    wlroots
    xwaylandvideobridge
    xwayland-run
    networkmanager
    network-manager-applet
    brightnessctl
    nautilus
    nwg-look
    papirus-icon-theme
    nordzy-hyprcursors
    python-pywal
    tty-colorscheme
)

# WARN: IF YOU ARE ON A NEW ARCH INSTALL HAVE NO DESKTOP AND WANT TO RICE A WINDOW MANAGER FROM SCRATCH THEN 
# ENABLE THIS AT THE END OF THE FILE AND YOU WILL HAVE A GOOD DESKTOP TO THEN RICE YOUR WINDOW MANAGER FROM
PREFERRED_DM=(
    cosmic
)

BLUE='\033[1;34m'
NC='\033[0m'

install_package_group() {
    local group_name="$1"
    shift
    local packages=("$@")

    echo -e "\n${BLUE}Installing ${group_name}...${NC}"
    if paru -S --needed --noconfirm "${packages[@]}"; then
        echo "✔️  ${group_name} installed successfully"
    else
        echo "❌  Failed to install ${group_name}"
        return 1
    fi
}

# WARN: Make sure to read and then edit this part as
# some of the important things are installed through here
install_package_group "System Packages" "${SYSTEM[@]}"
install_package_group "Graphics Packages" "${GRAPHICS[@]}"
install_package_group "Gaming Packages" "${GAMING_PKGS[@]}"
install_package_group "Base Packages" "${BASE_PKGS[@]}"
install_package_group "Terminal Emulators" "${TERM_PKGS[@]}"
install_package_group "GTK Dependencies" "${GTK_PKGS[@]}"
install_package_group "Development Languages and tools" "${DEVELOPMENT[@]}"
install_package_group "LSP's for neovim" "${LSP[@]}"
install_package_group "Formatters for neovim" "${FORMATTERS[@]}"
install_package_group "Browser" "${BROWSERS[@]}"
install_package_group "Pipewire packages" "${AUDIO[@]}"
install_package_group "Pipewire packages" "${VIDEO[@]}"
install_package_group "Bluetooth Packages" "${BLUETOOTH[@]}"
install_package_group "Hyprland packages" "${HYPR_PKGS[@]}"
# install_package_group "Preferred Desktop Manager" "${PREFERRED_DM[@]}"

echo "I HOPE THIS SCRIPT HELPED YOU WITH YOUR ARCH"
