#!/bin/sh

set -e

sudo pacman --noconfirm -S --needed pipewire pipewire-alsa pipewire-pulse pipewire-jack wireplumber alsa-utils pavucontrol helvum
systemctl --user enable --now pipewire.socket pipewire-pulse.socket wireplumber.service
