#!/bin/sh

set -e

echo "Installing dependencies"
if command -v paru >/dev/null 2>&1; then
    if paru -S --needed --noconfirm llama.cpp-vulkan; then
        echo "✔️  ${group_name} installed successfully"
        return 0
    fi
elif command -v yay >/dev/null 2>&1; then
    if yay -S --needed --noconfirm llama.cpp-vulkan; then
        echo "✔️  ${group_name} installed successfully"
        return 0
    fi
else
    echo "❌  No supported AUR or pacman helper found"
    return 1
fi


echo "Downloading Qwen2 for llm usage"
mkdir ~/LLMS
cd ~/LLMS
wget https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf
cd ~
