#!/bin/sh

Wall_DIR="$HOME/Wallpapers"
CWD="$(pwd)"

cd "$Wall_DIR" || exit

# Create a list of images
IFS=$'\n'
SELECTED_WALL=$(for a in *.jpg *.png *.jpeg; do
  echo "$a"
done | bemenu \
  -p "Select wallpaper:" \
  -l 8 \
  -i \
  --fn 'MesloLGS Nerd Font 20' \
  --nb '#1d1f21cc' \
  --nf '#c5c8c6' \
  --sb '#81a2becc' \
  --sf '#ffffff')

# If a selection was made, set the wallpaper
if [ -n "$SELECTED_WALL" ]; then
  FULL_PATH="$Wall_DIR/$SELECTED_WALL"
  bash "$HOME/mir/scripts/wset-backend" "$FULL_PATH"
fi

cd "$CWD" || exit
