#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image>"
  exit 1
fi

IMAGE="$1"

notify-send "Changing Theme" "Applying new wallpaper, please wait until confirmation..."

feh --bg-scale "$IMAGE"

matugen image "$IMAGE"

pkill -USR1 dwm

pkill -USR1 dunst

notify-send "Theme Applied" "Wallpaper updated successfully"
