#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_image>"
    exit 1
fi

IMAGE="$1"

notify-send "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

# Set wallpaper
swww img "$IMAGE" --transition-type="center" --transition-step=1 --transition-fps="60"

# Generate theme with Matugen
matugen image "$IMAGE"

# Reload Hyprland
hyprctl reload

# Restart Waybar
pkill waybar
waybar >/dev/null 2>&1 &

# Restart SwayNC
pkill swaync
swaync >/dev/null 2>&1 &

notify-send "Theme Applied" "Wallpaper and Theme updated successfully"
