#!/bin/sh

Wall_DIR="$HOME/Wallpapers/Pictures"

CWD="$(pwd)"

cd "$Wall_DIR" || exit

IFS=$'\n'

SELECTED_WALL=$(
    for a in *.jpg *.png *.jpeg; do
        echo "$a"
    done | wofi --dmenu --font "JetBrainsMono NF 20" --lines 8 --prompt "Select Wallpaper:"
)

if [ -n "$SELECTED_WALL" ]; then
    FULL_PATH="$Wall_DIR/$SELECTED_WALL"
    bash $HOME/senv/scripts/wset-backend "$FULL_PATH"
fi

cd "$CWD" || exit
